/**
 * Schreibt jinxes-embedded.js aus roles/jinxes-master.json (für file:// ohne fetch/CORS).
 * Nach Änderungen an jinxes-master.json: node scripts/embed-jinxes.js
 */
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const src = path.join(ROOT, 'roles', 'jinxes-master.json');
const out = path.join(ROOT, 'jinxes-embedded.js');
if (!fs.existsSync(src)) {
  console.error('Fehlt:', src);
  process.exit(1);
}
const data = JSON.parse(fs.readFileSync(src, 'utf8'));
const json = JSON.stringify(data);
const body =
  '/* Auto-generated by scripts/embed-jinxes.js — do not edit by hand */\n' +
  "'use strict';\n" +
  'var JINXES_MASTER_EMBEDDED = ' +
  json +
  ';\n';
fs.writeFileSync(out, body, 'utf8');
console.log('OK', out, '(' + (fs.statSync(out).size / 1024).toFixed(1) + ' KB)');
